apiVersion: v2
name: cybersage
description: A Helm chart for deploying Cybersage services to Kubernetes
type: application
version: 1.0.0
appVersion: "1.0"

keywords:
  - cybersage
  - security
  - analytics

home: https://github.com/kiwiProgrammer/cybersage-primary
sources:
  - https://github.com/kiwiProgrammer/cybersage-primary
